<%@ Page Title="Maintain Products and Prices" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="AdminMaintainProductsAndPrices.aspx.cs" Inherits="Project_Food_Ordering_System_2021_Prototype_1.Views.Admin.AdminMaintain_ProductsAndPrices" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Title" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            height: 20px;
        }

        .auto-style2 {
            height: 20px;
            width: 518px;
        }

        .auto-style3 {
            width: 518px;
            text-align: center;
        }

        .auto-style4 {
            height: 20px;
            width: 215px;
        }

        .auto-style5 {
            width: 215px;
        }

        .auto-style6 {
            width: 215px;
            height: 119px;
        }

        .auto-style7 {
            width: 518px;
            height: 119px;
        }

        .auto-style8 {
            height: 119px;
        }

        .auto-style9 {
            width: 215px;
            height: 26px;
        }

        .auto-style10 {
            width: 518px;
            height: 26px;
            text-align: center;
        }

        .auto-style11 {
            height: 26px;
        }

        .auto-style12 {
            height: 11px;
            width: 215px;
        }

        .auto-style13 {
            height: 11px;
            width: 518px;
        }

        .auto-style14 {
            height: 11px;
        }

        .auto-style15 {
            height: 49px;
            width: 215px;
        }

        .auto-style16 {
            height: 49px;
            width: 518px;
        }

        .auto-style17 {
            height: 49px;
        }
        .auto-style18 {
            height: 20px;
            width: 518px;
            text-align: center;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="contentBody" runat="server">
    <table style="width: 100%;">
        <tr>
            <td class="auto-style4"></td>
            <td class="auto-style18">
                <asp:Label ID="Label5" runat="server" Font-Size="18pt" Text="Edit Products And Prices"></asp:Label>
            </td>
            <td class="auto-style1"></td>
        </tr>
        <tr>
            <td class="auto-style4">&nbsp;</td>
            <td class="auto-style2">&nbsp;</td>
            <td class="auto-style1">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style15"></td>
            <td class="auto-style16">
                <asp:Label ID="Label6" runat="server" Text="Search products by name:"></asp:Label>
                &nbsp;&nbsp;
                <asp:TextBox ID="txtSearch" runat="server"></asp:TextBox>
                &nbsp;
                <asp:Button ID="btnFindProduct" runat="server" Text="Find Product" OnClick="btnFindProduct_Click" CssClass="myButtons" Width="120px
                    "/>
            </td>
            <td class="auto-style17"></td>
        </tr>
        <tr>
            <td class="auto-style6"></td>
            <td class="auto-style7">
                <asp:GridView ID="GridView1" 
                    runat="server"
                    AutoGenerateColumns="False"
                    CellPadding="4"
                    ForeColor="#333333"
                    GridLines="None"
                    Width="100%"
                    AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" 
                    OnRowDeleting="GridView1_RowDeleting" 
                    OnRowUpdated="GridView1_RowUpdated"
                    OnRowCancelingEdit="GridView1_RowCancelingEdit"
                    OnRowDeleted="GridView1_RowDeleted"
                    OnRowEditing="GridView1_RowEditing" 
                    OnRowUpdating="GridView1_RowUpdating">
                    <FooterStyle BackColor="Tan" />
                    <HeaderStyle BackColor="Tan" Font-Bold="True" />
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:TemplateField Visible="false">
                            <ItemTemplate>
                                <asp:Label ID="lblItem_ID" runat="server" Text='<%# Bind("Item_ID") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Item Name" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtItem_Name" runat="server" Text='<%# Bind("Item_Name") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblItem_Name" runat="server" Text='<%# Bind("Item_Name") %>'></asp:Label>
                            </ItemTemplate>

<HeaderStyle HorizontalAlign="Left"></HeaderStyle>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Item Price" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtItem_Price" runat="server" Text='<%# Bind("Item_Price") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblItem_Price" runat="server" Text='<%# Bind("Item_Price") %>'></asp:Label>
                            </ItemTemplate>

<HeaderStyle HorizontalAlign="Left"></HeaderStyle>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Item Category" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtCategory" runat="server" Text='<%# Bind("Category") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblCategory" runat="server" Text='<%# Bind("Category") %>'></asp:Label>
                            </ItemTemplate>

<HeaderStyle HorizontalAlign="Left"></HeaderStyle>
                        </asp:TemplateField>
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle HorizontalAlign="Right" BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle HorizontalAlign="Left" BackColor="#507CD1" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" ForeColor="#333333" Font-Bold="True" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
            </td>
            <td class="auto-style8"></td>
        </tr>
        <tr>
            <td class="auto-style12"></td>
            <td class="auto-style13"></td>
            <td class="auto-style14"></td>
        </tr>
        <tr>
            <td class="auto-style9"></td>
            <td class="auto-style10">
                <asp:Label ID="Label7" runat="server" Text="New Product Name:"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="txtNewName" runat="server"></asp:TextBox>
            </td>
            <td class="auto-style11"></td>
        </tr>
        <tr>
            <td class="auto-style9"></td>
            <td class="auto-style10">
                <asp:Label ID="Label8" runat="server" Text="New Product Price: "></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="txtNewPrice" runat="server"></asp:TextBox>
            </td>
            <td class="auto-style11"></td>
        </tr>
        <tr>
            <td class="auto-style5">&nbsp;</td>
            <td class="auto-style3">
                <asp:Label ID="Label9" runat="server" Text="New Product Category:"></asp:Label>
                &nbsp;<asp:DropDownList ID="DropDownList1" runat="server" Width="111px">
                    <asp:ListItem>Drink</asp:ListItem>
                    <asp:ListItem>Snack</asp:ListItem>
                    <asp:ListItem>Fast Food</asp:ListItem>
                    <asp:ListItem>Essential</asp:ListItem>
                </asp:DropDownList>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style5">&nbsp;</td>
            <td class="auto-style3">&nbsp;&nbsp;
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style5">
                <asp:Button ID="btnBack" runat="server" Text="Back" CssClass="myButtons" OnClick="btnBack_Click" Width="120px"/>
            </td>
            <td class="auto-style3">
                <asp:Button ID="btnAddProduct" runat="server" Text="Add Product" OnClick="btnAddProduct_Click" CssClass="myButtons" Width="120px"/>
            </td>
            <td>&nbsp;</td>
        </tr>
    </table>
</asp:Content>
